language: r
cache: packages

matrix:
  include:
    - r: release
      env: R_CODECOV=true
    - r: devel
    - os: linux
      addons:
        apt:
          packages: libnode-dev
    - os: osx
      brew_packages: v8
    - os: osx
      disable_homebrew: true

r_github_packages:
  - jimhester/covr
  - jeroen/V8

addons:
  apt:
    packages:
      - libv8-dev

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: change
    on_failure: change
  slack: ropensci:Uk8Kn3U3ngRV1p2YxLvXbQgw
