language: r
sudo: false
cache: packages
dist: trusty

r:
  - oldrel
  - release
  - devel

r_binary_install:
 - leaflet

addons:
  apt:
    packages:
      - libv8-dev

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: change
    on_failure: change
  slack: ropensci:Uk8Kn3U3ngRV1p2YxLvXbQgw
